### ISSUE TITLE
ThatOpen: C20-Institute-Var-2.ifc - no windows

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/test-models#10]
Link to the model in our this repo
https://github.com/bldrs-ai/test-models/blob/main/ifc/thatopen/ifcfiles/C20-Institute-Var-2.ifc

# Expected (web-ifc 0.0.55?)
https://thatopen.github.io/engine_web-ifc/demo/
<img width="766" alt="image" src="https://github.com/bldrs-ai/test-models/assets/3433606/6942c293-b18b-4aac-8da3-af21b44c34fd">

# Actual (bldrs-0.1.510-1)
[{Link to model in bldrs.ai, or note why note}](https://bldrs.ai/share/v/gh/bldrs-ai/test-models/main/ifc/thatopen/ifcfiles/C20-Institute-Var-2.ifc)
- Windows are hidden by the wall, it seems to be an issue with window openings 
<img width="931" alt="image" src="https://github.com/bldrs-ai/test-models/assets/3433606/ab6bcbb0-409d-46f0-a0ed-46b2a5988b97">

- Wall with windows is not rendered correctly
<img width="877" alt="image" src="https://github.com/bldrs-ai/test-models/assets/3433606/93fbda88-546f-45a8-98e7-ec0c8a8587cf">

**Comment by nickcastel50** [comment]
<img width="1414" alt="Screenshot 2024-06-18 at 4 27 35 PM" src="https://github.com/bldrs-ai/test-models/assets/17447690/a05bc5d6-53e1-4916-a56a-8aa6725b2d45">

Appears to be rendering properly now.
