### ISSUE TITLE
ThatOpen: FM_ARC_DigitalHub.ifc - does not load

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/test-models#12]
Link to the model in our repo
https://github.com/bldrs-ai/test-models/blob/main/ifc/thatopen/ifcfiles/FM_ARC_DigitalHub.ifc

# Expected (web-ifc 0.0.55?)
https://thatopen.github.io/engine_web-ifc/demo/
<img width="801" alt="image" src="https://github.com/bldrs-ai/test-models/assets/3433606/63b9594a-c2b0-44d5-bae2-1a49799631ec">

# Actual (bldrs-0.1.510-1)
https://bldrs.ai/share/v/gh/bldrs-ai/test-models/main/ifc/thatopen/ifcfiles/FM_ARC_DigitalHub.ifc
<img width="1378" alt="image" src="https://github.com/bldrs-ai/test-models/assets/3433606/f6ee4ed3-fa84-4a3b-974c-1cb5b57f57ad">

The model does not load.

**Comment by nickcastel50** [comment]
<img width="1133" alt="Screenshot 2024-06-18 at 2 18 17 PM" src="https://github.com/bldrs-ai/test-models/assets/17447690/438f3df3-75fc-47c0-a1db-744178f40f0f">

@OlegMoshkovich this also loads now

**Comment by pablo-mayrgundter** [comment]
Yep, loads
