### ISSUE TITLE
ThatOpen: ISSUE_068_ARK_NUS_skolebygg.ifc

### ISSUE THREAD

**Issue by OlegMoshkovich** [bldrs-ai/test-models#17]
Link to the model in our repo
https://github.com/bldrs-ai/test-models/blob/main/ifc/thatopen/ifcfiles/ISSUE_068_ARK_NUS_skolebygg.ifc

# Expected (web-ifc 0.0.55?)
https://thatopen.github.io/engine_web-ifc/demo/
<img width="670" alt="image" src="https://github.com/bldrs-ai/test-models/assets/3433606/a61d58e4-9cfc-447e-993f-83938a42faae">

# Actual (bldrs-0.1.510-1)
https://bldrs.ai/share/v/gh/bldrs-ai/test-models/main/ifc/thatopen/ifcfiles/ISSUE_068_ARK_NUS_skolebygg.ifc
<img width="824" alt="image" src="https://github.com/bldrs-ai/test-models/assets/3433606/c678b826-7cf1-4dd6-95be-0688d02080fe">

The side by side comparison is identical, two spaces on the left side of the building look suspicion, I think it is intentional position, but might be a problem with a transform.

**Comment by pablo-mayrgundter** [comment]
I can't see any issues at 0.1.596.  Closing
