### ISSUE TITLE
ThatOpen: Sample_entities.ifc

### ISSUE THREAD

**Issue by pablo-mayrgundter** [bldrs-ai/test-models#28]
[Link to the model in our this repo](https://github.com/bldrs-ai/test-models/blob/main/ifc/thatopen/ifcfiles/Sample_entities.ifc)

# Expected (web-ifc)
<img width="331" alt="image" src="https://github.com/bldrs-ai/test-models/assets/2480879/173fd9eb-7b7e-483c-bd18-c78c927a197e">

#
<img width="1434" alt="image" src="https://github.com/bldrs-ai/test-models/assets/2480879/b2decfd3-8ed5-4fe7-b4ae-4c70ac0fffd9">

**Comment by nickcastel50** [comment]
Fixed in latest Conway:

<img width="169" alt="Screenshot 2024-10-07 at 8 59 01 PM" src="https://github.com/user-attachments/assets/caf3ab9b-315a-4df6-a89b-3f243eb4f70e">
